# .gitpod.yml
image:
  file: Dockerfile

tasks:
  - name: PostgreSQL
    before: >
      brew install postgresql &&
      brew services start postgresql &&
      while ! pg_isready; do sleep 1; done &&
      createdb postgres &&
      psql -c "CREATE USER admin WITH PASSWORD 'LocalPasswordOnly';" postgres &&
      psql -c "GRANT ALL PRIVILEGES ON DATABASE postgres TO admin;" postgres
    command: sleep infinity

  - init: pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - charliermarsh.ruff
    - ms-python.black-formatter
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
  
